--https://www.hackerrank.com/challenges/the-pads/problem

SELECT CONCAT(NAME, '(', LEFT(OCCUPATION, 1), ')') OCC
FROM OCCUPATIONS
ORDER BY NAME;

SELECT CONCAT('There are a total of ',  AMOUNT, ' ', LOWER(OCCUPATION), 's.')
FROM 
(SELECT COUNT(NAME) AMOUNT, OCCUPATION
FROM OCCUPATIONS
GROUP BY OCCUPATION) A
ORDER BY AMOUNT
